name: encyclopedia
owner: jjohnson
categories:
- Proteomics
type: unrestricted
description: Mass Spec Data-Independent Acquisition (DIA) MS/MS analysis
long_description: |
  EncyclopeDIA is comprised of several algorithms for analysis of
  Data Independent Acquisition (DIA) Mass Spectrometry data.

homepage_url: https://bitbucket.org/searleb/encyclopedia/wiki/Home
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/encyclopedia/tools/encyclopedia
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} (from the EncyclopeDIA tool suite)"
suite:
  name: "suite_encyclopedia"
  description: EncyclopeDIA Data-Independent Acquisition (DIA) MS/MS Data Analysis 
exclude:
  - test-data/PrositLib.dlib
  - test-data/PeptidesForProsit.csv
  - test-data/BCS_hela.elib
  - test-data/uniprot_human.fasta
  - test-data/BCS_hela_narrow_3_2.mzML
  - test-data/BCS_hela_wide_500_900_1.mzML
  - test-data/YeastProteinFasta5.fasta
  - test-data/uniprot_tiny_human.fasta
  - test-data/BCS_hela_narrow_3_1.mzML
  - test-data/BCS_hela_wide_500_900_2.mzML
  - test-data/small_pan_human_library.dlib
  - test-data/PrositLib.csv
