name: encyclopedia
owner: galaxyp
categories:
- Proteomics
type: unrestricted
description: Mass Spec DIA ananysis
long_description: |
  EncyclopeDIA is comprised of several algorithms for analysis of
  Data Independent Acquisition (DIA) Mass Spectrometry data.

homepage_url: https://bitbucket.org/searleb/encyclopedia/wiki/Home
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/encyclopedia/tools/encyclopedia
